version: "3.8"

services:
  mongo:
    container_name: showcase
    image: mongo:8.0
    restart: always 
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: >
        mongosh --port 27017 --quiet --eval "
        try { rs.status() }
        catch (err) { 
          rs.initiate({_id: 'rs0', members: [{ _id: 0, host: 'localhost:27017' }]}) 
        }"
      interval: 5s
      timeout: 30s
      retries: 10
    volumes:
      - "mongo_data:/data/db"
      - "mongo_config:/data/configdb"

volumes:
  mongo_data:
  mongo_config:
